# Site settings
title: Nathan's Blog
email:
description: "Computers and what not."
baseurl: ""
url: "https://nathanpi8.github.io"
github_username: nathanpi8

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
